export const DMITDescriptions = (() => {
  const brainDominance = {
    left: {
      title: 'Left Brain Dominant',
      summary: 'Your left brain shows strong development. Think of it as your inner scientist — the part that loves facts, numbers, and step-by-step plans.',
      traits: ['Logical and analytical thinking', 'Strong language and verbal skills', 'Enjoys structure, rules, and planning', 'Detail-oriented and methodical', 'Thinks in words and numbers', 'Makes decisions based on facts'],
      careers: 'Scientist, Engineer, Accountant, Lawyer, Programmer, Data Analyst, Surgeon, Judge',
      learning: 'Learns best through lectures, reading, and step-by-step guides. Prefers structured instruction.',
      famous: 'Albert Einstein, Isaac Newton, Bill Gates, Warren Buffett',
      description: 'If your left brain is dominant, you are like a detective who loves solving puzzles. You think in a step-by-step way, you like having a plan, and you prefer knowing the rules before you start. You probably enjoy math, science, or reading. When faced with a problem, you break it into smaller pieces and solve them one by one. You are organized, punctual, and reliable. People come to you when they need someone who thinks clearly and makes sensible decisions. This is a powerful strength — just remember to also cultivate your creative side so you have the best of both worlds.'
    },
    right: {
      title: 'Right Brain Dominant',
      summary: 'Your right brain shows strong development. Think of it as your inner artist — the part that sees colors, patterns, and possibilities others cannot.',
      traits: ['Creative and intuitive thinking', 'Strong visual and spatial skills', 'Emotional intelligence and empathy', 'Prefers flexibility and spontaneity', 'Thinks in images and patterns', 'Big-picture thinker'],
      careers: 'Artist, Musician, Writer, Designer, Architect, Psychologist, Filmmaker, Counselor',
      learning: 'Learns best through visuals, hands-on activities, and creative projects. Prefers open-ended exploration.',
      famous: 'Leonardo da Vinci, Pablo Picasso, Mozart, Steve Jobs',
      description: 'If your right brain is dominant, you are like an artist who sees the world in colors and patterns. You often have a "gut feeling" about things that turns out to be right. You love creating things — art, music, stories, or new ways of solving problems. You dislike strict rules and prefer to find your own path. You are good at reading people\'s emotions. You may sometimes lose track of details because you are focused on the big picture. Your creative vision is your superpower — pair it with some organizational habits and you will be unstoppable.'
    },
    balanced: {
      title: 'Balanced Brain',
      summary: 'Both sides of your brain show similar levels of development. You can switch between logical and creative thinking with remarkable ease.',
      traits: ['Can switch between analytical and creative thinking', 'Adaptable and versatile', 'Well-rounded problem solver', 'Comfortable with both structure and flexibility'],
      careers: 'Entrepreneur, Manager, Teacher, Architect, Product Manager, Consultant',
      learning: 'Benefits from both structured and creative learning approaches. Can adapt to most teaching styles.',
      famous: 'Leonardo da Vinci, Benjamin Franklin',
      description: 'If both sides of your brain are highly developed, you have a superpower — you can think like a scientist AND like an artist. When a problem needs logic, you use your left brain. When it needs creativity, you use your right brain. This balance makes you very adaptable. The key is to keep developing both sides so neither grows lazy. People with balanced brains often make great leaders because they understand both rules and people.'
    }
  };

  const intelligences = {
    art: {
      name: 'Interpersonal Intelligence', shortName: 'Interpersonal', color: '#E74C3C',
      summary: 'You are "People Smart" \u2014 you understand others easily and work well in groups.',
      description: 'Interpersonal intelligence means you have a natural ability to understand other people. You can tell when someone is sad even if they are smiling. You know how to make people feel comfortable, how to work in a team, and how to lead a group. You are the person friends come to when they need advice or just someone to listen. Think of it like having a special radar that picks up on people\'s feelings and needs.',
      characteristics: ['Excellent communication skills', 'Empathetic and understanding', 'Natural leader or team player', 'Good at negotiation and conflict resolution', 'Can read social cues easily', 'Enjoys group activities and discussions'],
      strengths: ['Building relationships quickly', 'Leading teams effectively', 'Resolving conflicts peacefully', 'Understanding different perspectives'],
      weaknesses: ['May depend too much on others\' approval', 'Can lose your own identity in a group', 'May struggle working alone for long periods'],
      careers: 'Teacher, Psychologist, Manager, Salesperson, Politician, Diplomat, Social Worker, Counselor, HR Manager, PR Manager, Therapist',
      famousPeople: 'Mahatma Gandhi, Mother Teresa, Martin Luther King Jr., Oprah Winfrey, Nelson Mandela',
      studyTips: 'Study in groups, teach concepts to friends, discuss topics aloud, join debate clubs'
    },
    lit: {
      name: 'Literature Intelligence', shortName: 'Literature', color: '#8E44AD',
      summary: 'You are "Word Smart (Literary)" \u2014 you have a gift for creative and artistic use of language.',
      description: 'Literature intelligence means you have a special way with words \u2014 not just in everyday talking, but in creating beautiful, moving, and artistic expressions. You might love writing stories, poems, or plays. You notice the rhythm of words, the beauty of a well-written sentence, and the power of a good story. When you read a book, you don\'t just understand the words \u2014 you feel them.',
      characteristics: ['Masters of metaphor and wordplay', 'Create compelling narratives', 'Sensitive to rhythm and tone in language', 'Appreciate the beauty of written expression', 'Strong vocabulary and poetic sensibility', 'Drawn to novels, poetry, and literary criticism'],
      strengths: ['Creative writing and storytelling', 'Understanding deeper meanings in text', 'Evoking emotion through words', 'Critical literary analysis'],
      weaknesses: ['May over-analyze text', 'Can be overly subjective', 'May struggle with technical or dry writing'],
      careers: 'Novelist, Poet, Playwright, Screenwriter, Journalist, Literary Critic, Editor, Copywriter, Lyricist, Speechwriter',
      famousPeople: 'William Shakespeare, Jane Austen, Mark Twain, Rabindranath Tagore, J.K. Rowling, Leo Tolstoy',
      studyTips: 'Write summaries in your own words, create stories to remember facts, read widely, keep a journal'
    },
    img: {
      name: 'Imagination Intelligence', shortName: 'Imagination', color: '#F39C12',
      summary: 'You are "Idea Smart" \u2014 you constantly generate creative ideas and can envision possibilities others cannot.',
      description: 'Imagination intelligence is your ability to picture things that don\'t exist yet. You are a dreamer and an inventor. When others see a problem, you see ten possible solutions. You might daydream a lot, but those daydreams are actually your brain creating new ideas. You think in "what if" \u2014 what if we tried it this way? What if we combined these two things? This makes you naturally innovative and creative.',
      characteristics: ['Constantly generating new ideas', 'Daydreamer and visionary', 'Think in abstract and metaphorical terms', 'Can visualize complex scenarios', 'Unconventional problem solver', 'High tolerance for ambiguity'],
      strengths: ['Innovation and originality', 'Connecting seemingly unrelated concepts', 'Visualizing future possibilities', 'Thinking outside the box'],
      weaknesses: ['May struggle with follow-through', 'Can be impractical', 'May lose focus with too many ideas', 'May overpromise'],
      careers: 'Innovator, Designer, Film Director, Game Designer, Strategist, Futurist, Concept Artist, Creative Director, Inventor',
      famousPeople: 'Walt Disney, Nikola Tesla, J.R.R. Tolkien, Salvador Dali, Steve Jobs, Hayao Miyazaki',
      studyTips: 'Use mind maps, brainstorm before studying, connect topics to big ideas, allow creative expression in assignments'
    },
    gm: {
      name: 'Gross Motor Intelligence', shortName: 'Gross Motor', color: '#27AE60',
      summary: 'You are "Body Smart (Movement)" \u2014 you learn and express yourself through physical activity and whole-body movement.',
      description: 'Gross motor intelligence means your body is your greatest tool. You learn best when you are moving \u2014 running, jumping, dancing, playing sports. You have excellent coordination, balance, and timing. Sitting still in a classroom for hours is hard for you because your body WANTS to move. When you physically do something, you remember it forever.',
      characteristics: ['Excellent coordination and balance', 'Strong, agile, and physically fit', 'Excel in sports and athletic activities', 'Good sense of timing in movement', 'Learn best through physical activity', 'Natural athletic ability'],
      strengths: ['Physical performance and endurance', 'Quick physical reactions', 'Learning by doing', 'Body awareness and coordination'],
      weaknesses: ['May struggle with sedentary tasks', 'Can be restless in classroom settings', 'May need movement breaks', 'May neglect intellectual pursuits'],
      careers: 'Athlete, Dancer, PE Teacher, Fitness Trainer, Firefighter, Military, Choreographer, Stunt Performer, Physical Therapist, Sports Coach',
      famousPeople: 'Michael Jordan, Serena Williams, Usain Bolt, Muhammad Ali, Simone Biles',
      studyTips: 'Take movement breaks every 20 minutes, use gestures while memorizing, act out concepts, study while standing or walking'
    },
    mu: {
      name: 'Music Intelligence', shortName: 'Music', color: '#E67E22',
      summary: 'You are "Music Smart" \u2014 you have a natural sensitivity to rhythm, pitch, melody, and the emotional power of music.',
      description: 'Music intelligence means you have a special connection with sound and music. You can pick up rhythms easily, you might notice when someone sings off-key, and music can deeply affect your mood. You might find yourself humming, tapping, or moving to beats without even thinking about it. Learning becomes easier when you put information to music or rhythm.',
      characteristics: ['Recognize and reproduce musical patterns', 'Sensitive to pitch, rhythm, and tone', 'Naturally drawn to music', 'Can create and compose music', 'Music evokes strong emotional responses', 'Often hum, tap, or move rhythmically'],
      strengths: ['Musical creation and performance', 'Pattern recognition in sound', 'Emotional expression through music', 'Auditory memory'],
      weaknesses: ['May be distracted by noise', 'Can be overwhelmed in noisy environments', 'May struggle with non-musical subjects'],
      careers: 'Singer, Composer, Musician, Music Producer, Conductor, DJ, Sound Engineer, Music Therapist, Audio Engineer, Lyricist',
      famousPeople: 'Beethoven, Mozart, A.R. Rahman, Freddie Mercury, Ravi Shankar, Ed Sheeran',
      studyTips: 'Create songs or rhymes for memorization, use rhythm patterns, listen to background music while studying, connect topics to musical patterns'
    },
    vi: {
      name: 'Visual/Spatial Intelligence', shortName: 'Visual', color: '#3498DB',
      summary: 'You are "Picture Smart" \u2014 you think in images, see details others miss, and have strong spatial awareness.',
      description: 'Visual intelligence means you see the world in pictures. You might be great at drawing, reading maps, or arranging furniture. When someone explains something to you, you automatically create a mental picture of it. You notice colors, shapes, and spatial relationships that others overlook.',
      characteristics: ['Strong visual memory', 'Excellent sense of direction', 'Good at puzzles, mazes, and spatial games', 'Can visualize objects from different angles', 'Think in pictures and images', 'Appreciate visual aesthetics'],
      strengths: ['Mental visualization', 'Designing and drawing', 'Spatial reasoning', 'Photographic memory for images'],
      weaknesses: ['May struggle with purely verbal instruction', 'Can overlook details in favor of big picture', 'May have difficulty with sequential tasks'],
      careers: 'Architect, Pilot, Surgeon, Graphic Designer, Interior Designer, Photographer, Engineer, Animator, Fashion Designer',
      famousPeople: 'Frank Lloyd Wright, Amelia Earhart, Leonardo da Vinci, M.C. Escher, Ansel Adams',
      studyTips: 'Use diagrams and charts, color-code your notes, draw what you are learning, watch educational videos, create visual summaries'
    },
    intra: {
      name: 'Intrapersonal Intelligence', shortName: 'Intrapersonal', color: '#1ABC9C',
      summary: 'You are "Self Smart" \u2014 you have deep self-awareness and understand your own feelings, motivations, and goals.',
      description: 'Intrapersonal intelligence means you know yourself really well. You understand what makes you happy, what scares you, what motivates you, and what your strengths and weaknesses are. You probably enjoy spending time alone to think and reflect. When you have a problem, you look inside yourself for the answer first.',
      characteristics: ['Deep self-awareness and introspection', 'Strong sense of personal identity', 'Independent and self-directed', 'Good at self-reflection', 'Prefer working alone', 'Clear about personal values and goals'],
      strengths: ['Self-motivation', 'Independent thinking', 'Emotional self-regulation', 'Deep understanding of personal goals'],
      weaknesses: ['May isolate from others', 'Can be perceived as aloof', 'May overanalyze emotions', 'Tendency toward perfectionism'],
      careers: 'Therapist, Psychologist, Counselor, Entrepreneur, Philosopher, Writer, Researcher, Life Coach, Artist',
      famousPeople: 'Aristotle, Maya Angelou, Mahatma Gandhi, Socrates, Carl Jung, Helen Keller',
      studyTips: 'Study independently, set personal goals, keep a reflection journal, create a quiet study space, meditate before studying'
    },
    logic: {
      name: 'Logic/Mathematical Intelligence', shortName: 'Logic', color: '#2C3E50',
      summary: 'You are "Number/Reasoning Smart" \u2014 you excel at logical thinking, math, and solving complex problems step by step.',
      description: 'Logic intelligence means your brain works like a calculator and a detective combined. You love solving puzzles, you are good at math, and you think in cause-and-effect \u2014 "If this happens, then that will follow." When you face a problem, you don\'t guess \u2014 you figure it out logically.',
      characteristics: ['Excel at math and logical reasoning', 'Strong problem-solving abilities', 'Identify patterns and relationships', 'Think in cause-and-effect terms', 'Enjoy puzzles and strategy games', 'Methodical and systematic'],
      strengths: ['Analytical problem solving', 'Pattern recognition', 'Critical thinking', 'Systematic approach to challenges'],
      weaknesses: ['May neglect emotions', 'Can struggle with ambiguity', 'May find creative tasks challenging', 'May overthink simple problems'],
      careers: 'Mathematician, Scientist, Accountant, Programmer, Engineer, Actuary, Statistician, Data Scientist, Doctor, Economist',
      famousPeople: 'Albert Einstein, Bill Gates, Marie Curie, Stephen Hawking, Isaac Newton, Ada Lovelace',
      studyTips: 'Break topics into logical steps, solve practice problems, use mnemonics based on patterns, create outlines and frameworks'
    },
    fm: {
      name: 'Fine Motor Intelligence', shortName: 'Fine Motor', color: '#E91E63',
      summary: 'You are "Hand Smart" \u2014 you have excellent precision and dexterity in your hands and fingers.',
      description: 'Fine motor intelligence means your hands are incredibly skilled and precise. You can do detailed work with small objects \u2014 like threading a needle, building tiny models, or performing delicate surgeries. You learn best by touching and manipulating things. Your hand-eye coordination is exceptional.',
      characteristics: ['Excellent hand-eye coordination', 'Precise finger movements', 'Skilled at detailed handiwork', 'Good at crafts and model-making', 'Can handle small tools and instruments', 'Learn by touching and manipulating'],
      strengths: ['Precision and dexterity', 'Craftsmanship and detail work', 'Building and assembling', 'Musical instrument fingering'],
      weaknesses: ['May get frustrated with large-scale activities', 'Can be overly focused on detail', 'May struggle with gross physical tasks'],
      careers: 'Surgeon, Dentist, Watchmaker, Jeweler, Mechanic, Artist, Sculptor, Typist, Calligrapher, Chef, Woodworker',
      famousPeople: 'Michelangelo (sculpting), Dr. Ben Carson (neurosurgery), Vladimir Horowitz (pianist)',
      studyTips: 'Take notes by hand, build models of concepts, use flashcards you can hold, do hands-on experiments, practice with physical objects'
    },
    lang: {
      name: 'Linguistic Intelligence', shortName: 'Linguistic', color: '#9B59B6',
      summary: 'You are "Word Smart (Communication)" \u2014 you use language effectively to communicate, persuade, and explain.',
      description: 'Linguistic intelligence (communication focus) means you are skilled at using words to get your message across. While Literature intelligence is about creative and artistic writing, Linguistic intelligence is about effective communication \u2014 speaking clearly, writing persuasively, and explaining complex ideas simply.',
      characteristics: ['Persuasive and articulate speaker', 'Strong reading and writing comprehension', 'Can explain complex ideas clearly', 'Good at debates and arguments', 'Rapid language learning ability', 'Strong in verbal reasoning'],
      strengths: ['Clear communication', 'Persuasion and negotiation', 'Teaching and explaining', 'Language learning'],
      weaknesses: ['May talk too much', 'Can dominate conversations', 'May struggle with non-verbal communication', 'Can be overly argumentative'],
      careers: 'Lawyer, Politician, Broadcaster, Teacher, Journalist, Translator, Interpreter, Salesperson, Public Speaker, TV Host',
      famousPeople: 'Winston Churchill, Oprah Winfrey, Barack Obama, Martin Luther King Jr.',
      studyTips: 'Read aloud, explain concepts to others, use verbal mnemonics, participate in discussions, record and listen to study notes'
    },
    nat: {
      name: 'Naturalist Intelligence', shortName: 'Naturalist', color: '#16A085',
      summary: 'You are "Nature Smart" \u2014 you have a deep connection with the natural world and can recognize patterns in nature.',
      description: 'Naturalist intelligence means you feel at home in nature. You notice things about plants, animals, weather, and the environment that others miss. You might be the person who spots a rare bird, identifies a plant by its leaf, or predicts rain before the clouds gather. You understand how living things are connected in ecosystems.',
      characteristics: ['Can identify and classify flora and fauna', 'Sensitive to natural patterns and changes', 'Drawn to the outdoors', 'Good at recognizing weather patterns', 'Appreciate environmental conservation', 'Holistic understanding of ecosystems'],
      strengths: ['Classification and categorization', 'Environmental awareness', 'Pattern recognition in nature', 'Understanding of biological systems'],
      weaknesses: ['May struggle in purely indoor environments', 'Can be perceived as less "practical"', 'May neglect technology-based skills'],
      careers: 'Botanist, Biologist, Veterinarian, Geologist, Meteorologist, Environmental Scientist, Park Ranger, Farmer, Marine Biologist, Chef, Ecologist',
      famousPeople: 'Charles Darwin, Jane Goodall, David Attenborough, Rachel Carson, Steve Irwin',
      studyTips: 'Study outside when possible, connect topics to real-world examples, care for plants as study companions, use nature analogies for concepts'
    }
  };

  const fingerprintPersonalities = {
    'W1': { name: 'Target Centric (Concentric Whorl)', pattern: 'Ridges form concentric circles around a central point, like a bullseye target.', disc: 'D', discName: 'Dominant', color: '#E74C3C', traits: ['Strong-willed and determined', 'Goal-oriented with clear objectives', 'Independent and decisive', 'Natural leader who takes charge', 'Persistent and doesn\'t give up easily', 'Competitive and results-driven'], communicationStyle: 'Direct, assertive, gets to the point quickly. Says what they mean and means what they say.', strengths: 'Leadership, determination, focus, independence, decisiveness', weaknesses: 'Stubbornness, dominance, impatience, can be insensitive to others\' feelings', relationships: 'Wants to lead in the relationship; may struggle with compromise. Needs a partner who respects their drive but also stands their ground.', family: 'Protective and providing parent, but may be controlling. Needs to practice letting others make decisions too.', society: 'Respected leader, confident presence. Others naturally look to them for direction.', workplace: 'Takes initiative, drives results, inspires confidence. Can intimidate quieter team members if unaware.', description: 'You are like a determined captain steering a ship. Once you set a course, nothing can sway you from it. People admire your strength, but you need to remember that listening is also a form of power.' },
    'W2': { name: 'Spiral Whorl', pattern: 'Ridges spiral outward from the center in a clockwise or counter-clockwise pattern.', disc: 'I', discName: 'Influential', color: '#F39C12', traits: ['Expressive, enthusiastic, and sociable', 'Creative and spontaneous', 'Loves attention and recognition', 'Optimistic and energetic', 'Good at networking and persuasion', 'Flexible and adaptable'], communicationStyle: 'Animated, storytelling, persuasive, enthusiastic. Captivates audiences with energy and charm.', strengths: 'Charisma, persuasion, creativity, optimism, social skills', weaknesses: 'Disorganization, impulsiveness, over-commitment, may lack follow-through', relationships: 'Warm and affectionate, loves to make their partner feel special. May seek attention and validation.', family: 'Fun-loving and entertaining parent. May avoid difficult conversations or discipline.', society: 'Natural social butterflies, popular, center of attention. They connect different friend groups together.', workplace: 'Great presenters and motivators, persuasive salespeople. May need reminders to finish what they start.', description: 'You are like sunshine in a room \u2014 you light it up when you walk in. People are drawn to your energy and enthusiasm. Your challenge is staying focused long enough to see your big ideas through to completion.' },
    'W3': { name: 'Elongated Target Centric', pattern: 'Like Target Centric but vertically stretched/elongated.', disc: 'D/C', discName: 'Dominant-Compliant', color: '#C0392B', traits: ['Perfectionist with high standards', 'Detail-oriented and precise', 'Combines leadership with analytical thinking', 'Thorough in everything', 'Organized and systematic', 'High internal pressure to achieve'], communicationStyle: 'Detailed, factual, sometimes overly critical. Values precision in communication.', strengths: 'Precision, thoroughness, high standards, analytical ability', weaknesses: 'Perfectionism, criticism, rigidity, stress from self-imposed pressure', relationships: 'Loyal but demanding partner. Holds themselves and their partner to very high standards.', family: 'Provides structure and quality but may be overly strict or demanding.', society: 'Respected for quality work and reliability. May seem distant or hard to please.', workplace: 'Delivers excellent work but may miss deadlines due to perfectionism. Needs to learn "done is better than perfect."', description: 'You are driven by a need for excellence. Everything you do has to meet your high standards. You combine the determination of a leader with the precision of a craftsman. Your challenge is watching out for burnout from pushing yourself too hard.' },
    'W4': { name: 'Elongated Spiral', pattern: 'Like a Spiral Whorl but vertically stretched/elongated.', disc: 'I/S', discName: 'Influential-Steady', color: '#E67E22', traits: ['Creative but more deliberate', 'Combines sociability with sensitivity', 'Artistic with emotional depth', 'Patient and caring', 'Good listener who also loves to share', 'Can be indecisive considering multiple views'], communicationStyle: 'Warm, creative, thoughtful, emotionally expressive. Thinks before speaking but speaks from the heart.', strengths: 'Creativity with follow-through, empathy, balanced expression', weaknesses: 'Indecisiveness, emotional sensitivity, may overthink decisions', relationships: 'Deeply caring partner who expresses love creatively. Values emotional connection deeply.', family: 'Nurturing and creative presence in the family. Creates warm, artistic home environments.', society: 'Artistic contributors and community builders. They bring beauty and harmony to social groups.', workplace: 'Creative problem solvers who are also reliable team players. Good at bridging analytical and creative thinking.', description: 'You are a thoughtful creative soul \u2014 you have all the imagination of an artist but with enough patience to actually bring your ideas to life. Your challenge is making decisions \u2014 you can see so many beautiful possibilities that choosing just one feels like giving up on the others.' },
    'W5': { name: 'Double Loop Whorl', pattern: 'Two loop formations intertwine, creating a figure-8 or yin-yang pattern.', disc: 'D/I', discName: 'Dominant-Influential', color: '#8E44AD', traits: ['Dual-natured \u2014 can see multiple perspectives', 'Complex, multi-dimensional personality', 'Excellent at adapting to situations', 'Versatile and flexible', 'Good at mediation', 'Can be inconsistent or unpredictable'], communicationStyle: 'Adaptable \u2014 shifts style based on audience. Can argue both sides of a debate convincingly.', strengths: 'Versatility, adaptability, broad perspective, mediation skills', weaknesses: 'Inconsistency, internal conflict, indecisiveness, unpredictability', relationships: 'Can be exciting but confusing. Partner may feel they don\'t know which "version" they\'ll get today.', family: 'Flexible parent who adapts to each child\'s needs. May send mixed signals about expectations.', society: 'Natural bridge-builders between different social groups. Can fit in anywhere.', workplace: 'Great at roles requiring flexibility and switching between tasks. May seem unreliable due to shifting priorities.', description: 'You are like two people living in one body \u2014 but in a fascinating way! You can see both sides of every story, adapt to almost any situation, and relate to almost anyone. Your challenge? Sometimes even you don\'t know which path to take.' },
    'W6': { name: 'Imploding Whorl', pattern: 'Central pocket \u2014 ridges loop around a small whorl inside a larger loop pattern.', disc: 'S/C', discName: 'Steady-Compliant', color: '#27AE60', traits: ['Inner-focused with rich inner world', 'Contemplative and deeply reflective', 'Values security and stability', 'Sensitive and emotionally deep', 'Thoughtful and methodical', 'Strong need for safety; risk-averse'], communicationStyle: 'Careful, measured, thoughtful. Hesitates before speaking, choosing words with precision.', strengths: 'Depth of thought, sensitivity, careful analysis, loyalty', weaknesses: 'Anxiety, overthinking, shyness, resistance to change', relationships: 'Deeply committed but slow to open up. Once trust is built, they are loyal and caring partners.', family: 'Dependable and caring, but may worry too much about loved ones. Creates a secure home.', society: 'Quiet contributors and thoughtful observers. Their insights are valuable even though they don\'t seek the spotlight.', workplace: 'Thorough, reliable, prefers stable roles with clear expectations. Takes time to adjust to changes.', description: 'You have a rich, beautiful inner world that others rarely get to see. You think deeply about everything. You value safety and stability, and you are incredibly loyal. Your challenge is that your careful nature can sometimes hold you back from taking the risks that lead to growth.' },
    'W7': { name: 'Composite Whorl', pattern: 'A whorl with two or more deltas and complex ridge flow.', disc: 'Mixed', discName: 'Complex/Mixed', color: '#16A085', traits: ['Highly complex personality', 'Can be very creative and unconventional', 'Sees the world differently', 'Excellent at combining different ideas', 'May struggle with simple decisions', 'Independent thinker who resists categorization'], communicationStyle: 'Complex and multi-layered. May jump between topics. Sometimes misunderstood.', strengths: 'Originality, depth of understanding, synthesis of diverse ideas, independence', weaknesses: 'Confusion, inconsistency, difficulty fitting in, may feel alienated', relationships: 'Fascinating but challenging partner. Needs someone who appreciates and accepts their complexity.', family: 'Unique family member who may feel like the odd one out. Needs understanding and acceptance.', society: 'Often trendsetters or outliers. They see connections and possibilities others miss.', workplace: 'Brilliant in the right creative or analytical role. Struggles in rigid or highly structured environments.', description: 'You are a one-of-a-kind person whose mind works in ways that surprise even you. You don\'t fit neatly into categories. This makes you incredibly creative and original, but it can also make you feel like nobody quite "gets" you. Your superpower is synthesis \u2014 combining different ideas into something brand new.' },
    'W8': { name: "Target Centric Ulnar Peacock's Eye", pattern: 'Whorl-like pattern with a loop appearance \u2014 an "eye" shape with a central core.', disc: 'I/C', discName: 'Influential-Compliant', color: '#D35400', traits: ['Combines social skills with analytical thinking', 'Observant and detail-oriented while being sociable', 'Sharp-eyed and perceptive', 'Good at strategic social interactions', 'Values quality in relationships', 'Can be both creative and methodical'], communicationStyle: 'Articulate, precise yet warm. Good listeners who notice the details others miss.', strengths: 'Social intelligence, perception, balanced approach, quality-consciousness', weaknesses: 'Can be judgmental, may over-analyze social situations', relationships: 'Attentive partners who notice every detail. May hold the relationship to high standards.', family: 'Caring and observant family members. Keeps track of everyone\'s needs with precision.', society: 'Social connectors who bring quality and warmth to community interactions.', workplace: 'Excellent at roles requiring both social skills and accuracy \u2014 HR, quality management, diplomacy.', description: 'You have the rare gift of being socially skilled AND detail-oriented. You notice things about people that others miss. Your challenge is balancing your desire for social connection with your high standards for quality.' },
    'W9': { name: "Spiral Ulnar Peacock's Eye", pattern: 'Spiral variant of the Peacock\'s Eye pattern with ulnar loop influence.', disc: 'I/C', discName: 'Influential-Compliant', color: '#D35400', traits: ['Creative with social awareness', 'Spiritually inclined yet analytical', 'Combines imagination with precision', 'Good at both artistic and structured work', 'May feel tension between freedom and order'], communicationStyle: 'Creative expression balanced with thoughtful precision. Engaging yet accurate.', strengths: 'Creative-analytical balance, spiritual awareness, versatility', weaknesses: 'Internal tension between creative freedom and need for structure, may feel misunderstood', relationships: 'Deeply romantic with exacting standards. Seeks a partner who shares both creative and spiritual interests.', family: 'Creates a home filled with both beauty and order. Encourages children\'s creativity within structure.', society: 'Brings both artistic vision and practical organization to community efforts.', workplace: 'Excels in roles blending creativity with quality \u2014 design management, creative direction with timelines.', description: 'You are the bridge between creativity and structure. You can dream up brilliant ideas AND create the plan to make them real. Your challenge is the internal tug-of-war between wanting freedom and needing things to be "just right."' },
    'W10': { name: "Target Centric Radial Peacock's Eye", pattern: 'Target centric variant with radial loop influence.', disc: 'I/C', discName: 'Influential-Compliant', color: '#D35400', traits: ['Combines determination with social grace', 'Goal-driven yet people-aware', 'Perceptive and strategic', 'Independent yet collaborative', 'High standards with warmth'], communicationStyle: 'Both assertive and diplomatic. Can champion ideas persuasively while respecting others.', strengths: 'Strategic thinking, social perception, goal orientation with empathy', weaknesses: 'May set impossibly high standards, can be overly strategic in relationships', relationships: 'A driven partner who also deeply cares. May need to be less strategic and more vulnerable.', family: 'Ambitious for family success while nurturing each member. May place high expectations.', society: 'Respected community members who combine leadership with service.', workplace: 'Natural leaders in quality-focused teams \u2014 project management, consulting, strategic roles.', description: 'You are a strategic soul \u2014 you combine the drive of a leader with the sensitivity of a counselor. You set ambitious goals AND care about the people helping you reach them. Your challenge is learning when to stop strategizing and start being spontaneous.' },
    'W11': { name: "Spiral Radial Peacock's Eye", pattern: 'Spiral variant with radial loop influence.', disc: 'I/C', discName: 'Influential-Compliant', color: '#D35400', traits: ['Creative independence with social awareness', 'Questions norms thoughtfully', 'Combines originality with strategic thinking', 'Good at visionary yet practical work', 'May struggle balancing conformity and innovation'], communicationStyle: 'Thoughtful originality \u2014 shares unique perspectives in engaging ways.', strengths: 'Original strategic thinking, creative independence, social perceptiveness', weaknesses: 'May overthink, tension between fitting in and standing out', relationships: 'A unique partner who values both connection and independence. Needs intellectual stimulation.', family: 'Encourages independent thinking in family while maintaining close bonds.', society: 'Visionary contributors who bring fresh perspectives to community problems.', workplace: 'Thrives in innovation-focused roles that value both creativity and strategy.', description: 'You are a creative independent thinker who also understands people. You can question the status quo in a way that doesn\'t alienate. Your challenge is finding environments where your originality is valued rather than suppressed.' },
    'L': { name: 'Ulnar Loop', pattern: 'Ridges flow in from the thumb side and curve toward the little finger side. Most common pattern (~60%).', disc: 'S', discName: 'Steady', color: '#3498DB', traits: ['Calm, patient, and dependable', 'Good listeners and team players', 'Prefer harmony and avoid conflict', 'Consistent and reliable', 'Loyal and supportive', 'Process-oriented, follows established methods'], communicationStyle: 'Soft-spoken, supportive, listens before speaking. Creates a safe space for others to share.', strengths: 'Reliability, patience, teamwork, loyalty, consistency', weaknesses: 'Resistance to change, indecisiveness, may be passive, struggles with confrontation', relationships: 'Devoted, stable partner who avoids conflict at all costs. Creates a peaceful, nurturing relationship.', family: 'Nurturing and provides stability. May be too accommodating, letting others take advantage of their kindness.', society: 'Peacemakers and community stabilizers. They keep groups together and maintain harmony.', workplace: 'Reliable team members who support rather than lead. Avoid risk and prefer predictable roles.', description: 'You are the steady rock that others lean on. You are patient, kind, and always there when someone needs you. Your challenge is learning to speak up for yourself and embrace change, because growth often requires stepping out of your comfort zone.' },
    'R': { name: 'Radial Loop', pattern: 'Ridges flow in from the little finger side and curve toward the thumb side. Less common (~4%).', disc: 'I/S', discName: 'Influential-Steady', color: '#2980B9', traits: ['Independent thinker who questions norms', 'Goes against the grain', 'Combines social skills with independent judgment', 'Creative problem-solver', 'May challenge conventional wisdom', 'Friendly but retains individuality'], communicationStyle: 'Thoughtful, sometimes contrarian, engaging. Offers unique perspectives respectfully.', strengths: 'Independent thinking, insight, creativity, social skills with conviction', weaknesses: 'Can be contrary, may resist authority, sometimes isolated for going against the flow', relationships: 'Engaging partner who needs independence. Values both connection and personal freedom.', family: 'May challenge family norms. Has a strong independent streak that family needs to respect.', society: 'Independent contributors often seen as "the different one" who brings fresh perspectives.', workplace: 'Good at challenging the status quo constructively. Needs autonomy to thrive.', description: 'You march to the beat of your own drum \u2014 and it\'s a catchy rhythm. While you are friendly and social, you have a strong independent streak. You question things that everyone else accepts. Your challenge is balancing your need to go your own way with the need to fit into teams.' },
    'L1': { name: 'Ulnar Falling Loop', pattern: 'Like an Ulnar Loop but with falling/declining ridge lines.', disc: 'S', discName: 'Steady (with anxiety tendency)', color: '#5DADE2', traits: ['Generally steady but with underlying worry', 'May be prone to stress and anxiety', 'Caring but can be overwhelmed', 'Needs reassurance and support', 'Works hard to overcome insecurities', 'Creative under supportive conditions'], communicationStyle: 'Tentative, seeks reassurance, may second-guess themselves.', strengths: 'Sensitivity, hard work, empathy, resilience when supported', weaknesses: 'Anxiety, self-doubt, need for constant reassurance, may worry excessively', relationships: 'Needs a supportive, reassuring partner. Can be deeply loving once they feel safe.', family: 'Caring and attentive but may transfer anxiety to family members. Needs to manage own stress first.', society: 'Gentle contributors who prefer supportive social environments. May avoid large or unfamiliar groups.', workplace: 'Needs supportive management and clear expectations. Thrives when given encouragement and structure.', description: 'You are like a gentle stream \u2014 calm on the surface but with deep currents underneath. You are caring, sensitive, and hardworking, but you sometimes worry more than you need to. Your challenge is building inner confidence and trusting in your own abilities, because you are more capable than you realize.' },
    'R1': { name: 'Radial Falling Loop', pattern: 'Like a Radial Loop but with falling/declining ridge lines.', disc: 'I', discName: 'Influential (with stress tendency)', color: '#48C9B0', traits: ['Independent but with underlying tension', 'Creative but may feel misunderstood', 'Questions norms but lacks confidence to act', 'Internal conflict between conformity and independence', 'Needs encouragement to express uniqueness', 'Sensitive to criticism'], communicationStyle: 'Cautious creative expression. May hold back their true thoughts until they feel safe.', strengths: 'Depth of thought, creativity, unique perspective, originality when encouraged', weaknesses: 'Self-doubt, emotional volatility, hesitation, conflict between fitting in and standing out', relationships: 'A complex, creative partner who needs someone who appreciates and encourages their uniqueness.', family: 'May feel misunderstood by family. Thrives with relatives who celebrate their differences.', society: 'Cautious contributors who have original perspectives to offer. Need the right community to shine.', workplace: 'Thrives with understanding mentorship and creative freedom. Shrinks under harsh criticism.', description: 'You are a creative soul who sometimes feels like a bird in a cage of your own making. You have bold, original ideas but aren\'t always confident enough to share them. Your challenge is learning to trust your own voice and share your unique vision.' },
    'X1': { name: 'Plain Arch', pattern: 'Ridges rise gently in the center like a hill or wave, then flow to the other side.', disc: 'C', discName: 'Compliant', color: '#95A5A6', traits: ['Practical, down-to-earth, matter-of-fact', 'Accepting of authority and rules', 'Tends to follow rather than lead', 'Content with routine and predictability', 'Loyal, honest, and reliable', 'Simple, straightforward personality'], communicationStyle: 'Simple, direct, factual. Says what needs to be said without embellishment.', strengths: 'Reliability, honesty, loyalty, practicality, steadiness', weaknesses: 'Lack of initiative, rigidity, may not think creatively, may resist trying new approaches', relationships: 'Stable, predictable, and loyal partner. May lack excitement but provides unwavering support.', family: 'Dependable and follows family traditions. Provides a steady, predictable home environment.', society: 'Law-abiding, contributes through steady, consistent work. The backbone of any community.', workplace: 'Follows instructions well, reliable but may need direction. Excellent at maintaining processes.', description: 'You are the foundation that holds everything together. You are practical, honest, and do exactly what you say you will do. Your challenge is finding the courage to try new things and take initiative when you see something that could be improved.' },
    'X2': { name: 'Tented Arch', pattern: 'Like a plain arch but the center rises sharply to a peak/tent shape.', disc: 'C/D', discName: 'Compliant-Dominant', color: '#7F8C8D', traits: ['More intense than plain arch', 'Driven by beliefs and convictions', 'Can be stubborn when challenged', 'Detail-oriented but with passion', 'Strong sense of right and wrong', 'Quick to react to perceived injustice'], communicationStyle: 'Intense, opinionated, principled, may be blunt when values are at stake.', strengths: 'Integrity, conviction, attention to detail, passion for truth', weaknesses: 'Emotional reactivity, stubbornness, can be harsh when triggered, inflexible', relationships: 'Loyal but demanding partner who holds strongly to their principles and values.', family: 'Strong moral compass parent. May be strict about values but deeply cares about family\'s wellbeing.', society: 'Principled community members who stand up for what they believe in.', workplace: 'Thorough and principled workers. May need to manage emotional responses in high-pressure situations.', description: 'You are a person of deep conviction \u2014 when you believe something, you believe it with your whole heart. Your challenge is managing the intensity of your convictions so they become a source of strength rather than conflict.' },
    'X3': { name: 'Tented Arch with Ulnar Loop', pattern: 'Tented arch combined with an ulnar loop pattern.', disc: 'C/S', discName: 'Compliant-Steady', color: '#7F8C8D', traits: ['Principled yet gentle', 'Combines conviction with compassion', 'Detail-oriented but caring', 'Values both accuracy and harmony', 'May struggle between standards and peace', 'Reliable with a warm heart'], communicationStyle: 'Caring but precise. Expresses standards gently but firmly.', strengths: 'Balanced judgment, caring precision, principled compassion, reliability with warmth', weaknesses: 'Internal tension between standards and harmony, may over-accommodate while resenting it', relationships: 'A caring partner who also holds strong values. Balances nurturing with principled expectations.', family: 'A warm yet structured parent who creates both safety and standards in the home.', society: 'Community members who bring both moral clarity and compassion to social issues.', workplace: 'Diligent and caring colleagues. Ensure quality while maintaining team harmony.', description: 'You are a rare combination of principled and gentle \u2014 you hold strong beliefs but express them with kindness. Your challenge is not letting your desire for harmony make you compromise on your core values.' },
    'X4': { name: 'Tented Arch with Radial Loop', pattern: 'Tented arch combined with a radial loop pattern.', disc: 'C/I', discName: 'Compliant-Influential', color: '#7F8C8D', traits: ['Principled yet expressive', 'Holds strong opinions but communicates engagingly', 'Combines accuracy with social skill', 'Can be both critical and charming', 'Independent thinker within rules'], communicationStyle: 'Engaging and principled. Convinces others through both logic and personality.', strengths: 'Persuasive conviction, social intelligence with standards, principled leadership', weaknesses: 'May preach, internal conflict between social acceptance and integrity', relationships: 'A passionate partner who communicates their values compellingly.', family: 'Engages family in important discussions and values. Creates an intellectually stimulating home.', society: 'Vocal community advocates who combine charm with conviction.', workplace: 'Effective in quality-focused, people-facing roles \u2014 compliance training, quality assurance.', description: 'You combine strong principles with the ability to communicate them persuasively. You don\'t just believe in doing the right thing \u2014 you can convince others to do it too. Your challenge is ensuring your persuasive skills serve your principles rather than your need for social approval.' },
    'W': { name: 'Accidental Whorl', pattern: 'Irregular whorl pattern that doesn\'t fit standard sub-classifications.', disc: 'Variable', discName: 'Variable/Dominant', color: '#E74C3C', traits: ['Unique and unconventional personality', 'Unpredictable and highly individual', 'Combines traits from multiple whorl types', 'Often very creative and original thinkers', 'Does not fit neatly into categories', 'Independent and self-reliant'], communicationStyle: 'Unpredictable \u2014 varies significantly based on context and mood.', strengths: 'Originality, independence, unique perspective, adaptability', weaknesses: 'Difficulty fitting in, inconsistency, may feel isolated or misunderstood', relationships: 'Needs a partner who accepts and celebrates their uniqueness. Cannot be put in a box.', family: 'Unconventional but caring family member. May feel like the "different one" in the family.', society: 'Trendsetters and outliers. They see the world in ways others cannot.', workplace: 'Thrives in creative or autonomous roles. Struggles in rigid or heavily structured environments.', description: 'You are truly one of a kind. You don\'t fit into any standard category, and that is your greatest gift. Your challenge is finding environments and people who appreciate your uniqueness rather than trying to fit you into a predetermined mold.' }
  };

  const discTypes = {
    D: { name: 'Dominance', fullTitle: 'D \u2014 Dominance (Outgoing + Task-Oriented)', color: '#C0392B', focus: 'Results, control, power', motivatedBy: 'Competition, winning, authority, direct results', fear: 'Being taken advantage of, losing control', strengths: 'Decisive, direct, confident, problem-solver, takes initiative', weaknesses: 'Impatient, blunt, may overlook feelings, can be domineering', communication: 'Direct, bottom-line, results-focused. Wants the summary, not the story.', idealEnvironment: 'Fast-paced, competitive, autonomous', underStress: 'Becomes more demanding and autocratic', careers: 'CEO, Entrepreneur, Attorney, Police Officer, Sales Director, Surgeon', description: 'D-type people are the drivers and decision-makers. They focus on results and want to be in control. They are assertive, competitive, and get things done quickly. In a group project, they are the one who says "Let\'s do it this way and get it done!" While their determination is admirable, they need to work on patience and listening to others\' ideas.' },
    I: { name: 'Influence', fullTitle: 'I \u2014 Influence (Outgoing + People-Oriented)', color: '#F39C12', focus: 'Enthusiasm, collaboration, social recognition', motivatedBy: 'Social recognition, group activities, friendly relationships', fear: 'Loss of influence, social rejection, being ignored', strengths: 'Enthusiastic, optimistic, persuasive, collaborative, sociable', weaknesses: 'Disorganized, impulsive, overly talkative, lacks follow-through', communication: 'Expressive, storytelling, enthusiastic, warm. Loves the story, not just the summary.', idealEnvironment: 'Social, collaborative, recognition-oriented', underStress: 'Becomes more dramatic and disorganized', careers: 'PR Manager, Sales, Creative Director, Travel Agent, Entertainer, Host', description: 'I-type people are the life of the party. They are enthusiastic, optimistic, and make everything more fun. They are great communicators who can persuade and inspire others. While their enthusiasm is infectious, they need to work on follow-through and organization.' },
    S: { name: 'Steadiness', fullTitle: 'S \u2014 Steadiness (Reserved + People-Oriented)', color: '#2980B9', focus: 'Stability, cooperation, support', motivatedBy: 'Stable environment, sincere appreciation, cooperation', fear: 'Sudden change, instability, loss of security', strengths: 'Patient, reliable, good listener, team player, supportive', weaknesses: 'Resists change, indecisive, avoids conflict, passive', communication: 'Gentle, thoughtful, listens first, supportive. Creates a safe space.', idealEnvironment: 'Stable, predictable, cooperative', underStress: 'Withdraws, becomes more passive and silent', careers: 'Counselor, HR Director, Nurse, Teacher, Therapist, Librarian', description: 'S-type people are the steady, reliable foundation of any group. They are patient, great listeners, and always there when you need them. They value harmony and stability. While their patience and loyalty are invaluable, they need to work on speaking up for themselves and embracing change.' },
    C: { name: 'Conscientiousness', fullTitle: 'C \u2014 Conscientiousness (Reserved + Task-Oriented)', color: '#27AE60', focus: 'Accuracy, quality, structure', motivatedBy: 'Opportunities to use expertise, quality, knowledge', fear: 'Criticism, being wrong, disorder, making mistakes', strengths: 'Analytical, detail-oriented, organized, logical, accurate', weaknesses: 'Perfectionist, overly critical, may overanalyze, risk-averse', communication: 'Factual, precise, data-driven, systematic. Wants the details, not just the summary.', idealEnvironment: 'Structured, detail-oriented, independent', underStress: 'Becomes more withdrawn and perfectionist', careers: 'Software Engineer, Actuary, Scientist, Economist, Accountant, Data Analyst', description: 'C-type people are the quality controllers and detail masters. They want everything to be accurate and correct. They are analytical, systematic, and thorough. While their attention to detail is exceptional, they need to work on accepting "good enough" sometimes.' }
  };

  const hollandTypes = {
    R: { name: 'Realistic', title: 'R \u2014 Realistic (Doers)', color: '#E67E22', description: 'Hands-on people who love working with tools, machines, animals, or the outdoors. They are practical and prefer concrete results.', traits: 'Practical, physical, hands-on, concrete, stable, outdoorsy', careers: 'Engineer, Mechanic, Farmer, Chef, Athlete, Electrician, Pilot, Firefighter, Surgeon', ancientRole: 'Hunters \u2014 the providers who kept the tribe alive through physical skill' },
    I: { name: 'Investigative', title: 'I \u2014 Investigative (Thinkers)', color: '#2C3E50', description: 'Curious minds who love asking questions and finding answers through research and analysis. They are independent thinkers who value knowledge above all.', traits: 'Analytical, intellectual, scientific, curious, independent, reserved', careers: 'Scientist, Researcher, Doctor, Psychologist, Pharmacist, Professor, Data Scientist, Physicist', ancientRole: 'Shamans \u2014 the wise ones who understood the mysteries of the world' },
    A: { name: 'Artistic', title: 'A \u2014 Artistic (Creators)', color: '#9B59B6', description: 'Creative souls who express themselves through art, music, writing, or design. They value originality and beauty, and prefer unstructured environments.', traits: 'Creative, original, independent, expressive, intuitive, unconventional', careers: 'Artist, Writer, Musician, Designer, Architect, Actor, Photographer, Filmmaker', ancientRole: 'Artisans \u2014 the creators who brought beauty and meaning to the tribe' },
    S: { name: 'Social', title: 'S \u2014 Social (Helpers)', color: '#27AE60', description: 'Compassionate people who love helping, teaching, and supporting others. They thrive in collaborative environments and find fulfillment in making a positive difference.', traits: 'Helpful, friendly, empathetic, patient, cooperative, nurturing', careers: 'Teacher, Counselor, Nurse, Social Worker, Doctor, Therapist, HR Manager, Dietitian', ancientRole: 'Healers \u2014 the caretakers who kept the community healthy and connected' },
    E: { name: 'Enterprising', title: 'E \u2014 Enterprising (Persuaders)', color: '#E74C3C', description: 'Natural leaders who love to influence, persuade, and make things happen. They are confident, ambitious, and comfortable taking risks.', traits: 'Persuasive, confident, ambitious, energetic, adventurous, dominant', careers: 'CEO, Lawyer, Sales Manager, Entrepreneur, Politician, Marketing Director, Stockbroker', ancientRole: 'Leaders \u2014 the chiefs who guided the tribe to prosperity' },
    C: { name: 'Conventional', title: 'C \u2014 Conventional (Organizers)', color: '#3498DB', description: 'Organized and detail-oriented people who love systems, data, and structure. They are efficient, careful, and excel at keeping things running smoothly.', traits: 'Organized, detail-oriented, structured, careful, efficient, conforming', careers: 'Accountant, Actuary, Librarian, Financial Analyst, Office Manager, Paralegal, Bookkeeper', ancientRole: 'Lorekeepers \u2014 the record-keepers who preserved the tribe\'s knowledge and history' }
  };

  const mckenzieTypes = {
    Analytic: { name: 'Analytic', color: '#2C3E50', description: 'Analytic thinkers process information through logic and step-by-step analysis. They break problems into components and solve them systematically. They love data, evidence, and clear reasoning. When making decisions, they list pros and cons and act based on what the evidence tells them.', strengths: 'Logical reasoning, systematic problem-solving, data analysis, precision', challenges: 'May overthink, can be slow to act, may neglect emotions' },
    Introspective: { name: 'Introspective', color: '#8E44AD', description: 'Introspective thinkers process information through inner reflection and contemplation. They think deeply about meaning, purpose, and significance. When making decisions, they look inward, consider their values, and choose based on what feels truly meaningful. They tend to be reflective and thoughtful.', strengths: 'Deep understanding, wisdom, self-awareness, meaning-making', challenges: 'May isolate, can be slow to share ideas, may seem detached' },
    Interactive: { name: 'Interactive', color: '#E74C3C', description: 'Interactive thinkers process information through social exchange and discussion. They learn by talking, sharing, and connecting with others. They value harmony, relationships, and connection. When making decisions, they seek input from others and consider how it affects people.', strengths: 'Social intelligence, communication, relationship building, collaboration', challenges: 'May over-rely on others, can avoid independent thinking, may struggle alone' }
  };

  const quotients = {
    IQ: { name: 'Intelligence Quotient', color: '#6366F1', description: 'IQ measures your cognitive abilities \u2014 how well you can think logically, solve problems, understand complex ideas, and learn quickly. Think of it as your brain\'s processing speed and capacity.', interpretation: 'In DMIT, IQ is derived from your overall ridge count analysis. Higher ridge counts generally correlate with higher cognitive potential. BUT \u2014 IQ is NOT a fixed destiny. It represents potential that must be developed through learning and practice.', ranges: [{ range: 'Below 70', label: 'Below average \u2014 may need additional learning support' }, { range: '70-85', label: 'Borderline \u2014 may need focused learning strategies' }, { range: '85-115', label: 'Average \u2014 this is where most people fall' }, { range: '115-130', label: 'Above average \u2014 quick learner' }, { range: '130-145', label: 'Gifted \u2014 exceptional cognitive ability' }, { range: '145+', label: 'Highly gifted \u2014 extraordinary cognitive potential' }], improveTip: 'Read widely, solve puzzles, learn new skills, practice critical thinking, stay curious about the world' },
    EQ: { name: 'Emotional Quotient', color: '#22C55E', description: 'EQ measures your emotional intelligence \u2014 how well you understand your own feelings AND other people\'s feelings. It\'s about knowing when you are angry, sad, or happy, and being able to manage those emotions. Many experts believe EQ is MORE important than IQ for success in life.', components: ['Self-awareness \u2014 recognizing your own emotions', 'Self-regulation \u2014 managing your emotions', 'Motivation \u2014 using emotions to drive achievement', 'Empathy \u2014 understanding others\' emotions', 'Social skills \u2014 handling relationships'], interpretation: 'In DMIT, EQ is derived from fingerprint patterns related to interpersonal and intrapersonal brain areas. Higher EQ indicates better emotional regulation and relationship skills.', improveTip: 'Practice empathy, keep an emotions journal, pause before reacting, listen actively, seek feedback' },
    CQ: { name: 'Creativity Quotient', color: '#F59E0B', description: 'CQ measures your creative thinking ability \u2014 how well you can come up with original ideas, think outside the box, and find new solutions to old problems.', interpretation: 'In DMIT, CQ is derived from whorl patterns and right-brain indicators. Higher CQ means more innovation potential.', improveTip: 'Try new hobbies, ask "what if" questions, brainstorm without judging, combine ideas from different fields, allow yourself to daydream' },
    AQ: { name: 'Adversity Quotient', color: '#EF4444', description: 'AQ measures your resilience \u2014 how well you bounce back from setbacks, failures, and difficult situations. Think of it as your "never give up" score.', components: ['Control \u2014 how much control you feel over adverse events', 'Ownership \u2014 how much responsibility you take to improve things', 'Reach \u2014 how far the adversity extends into other life areas', 'Endurance \u2014 how long you believe the adversity will last'], levels: [{ level: 'Climbers (High AQ)', description: 'Thrive on challenges, persistent, resilient, view setbacks as stepping stones' }, { level: 'Campers (Medium AQ)', description: 'Do enough to get by, may plateau, survive but don\'t necessarily thrive' }, { level: 'Quitters (Low AQ)', description: 'Easily overwhelmed, give up quickly, view setbacks as permanent failures' }], improveTip: 'Reframe failures as learning, take small risks, build a support network, practice perseverance, celebrate small wins' }
  };

  const atdAngle = {
    description: 'The ATD angle is measured on your palm print. It tells us how quickly your brain processes new information. Think of it like a computer\'s processor speed \u2014 a smaller angle means faster processing.',
    interpretation: [
      { range: 'Below 35\u00B0', speed: 'Very Fast Learner', description: 'You absorb information like a sponge. New concepts come naturally to you.' },
      { range: '35\u00B0\u201340\u00B0', speed: 'Fast Learner', description: 'You pick up new ideas quickly and understand concepts faster than most people.' },
      { range: '40\u00B0\u201345\u00B0', speed: 'Average Learner', description: 'You learn at a normal pace \u2014 this describes most people. Consistent study works well for you.' },
      { range: '45\u00B0\u201350\u00B0', speed: 'Moderate Learner', description: 'You may need a bit more time and repetition. Multiple approaches to learning help.' },
      { range: '50\u00B0\u201355\u00B0', speed: 'Slow Learner', description: 'You benefit from extra time, patience, and alternative teaching methods. Your intelligence is just as high \u2014 you just process differently.' },
      { range: 'Above 55\u00B0', speed: 'Needs Support', description: 'You need significant support and specialized teaching approaches. With the right help, you can still achieve great things.' }
    ],
    importantNote: 'The ATD angle measures processing speed, NOT intelligence. A person with a larger angle may be equally intelligent but simply process information more slowly. Different is not less.'
  };

  const streamRecommendation = {
    Science: { name: 'Science Stream', color: '#2C3E50', description: 'The Science stream is ideal if you are strong in logical thinking, mathematics, and analytical problem-solving. You enjoy understanding how things work and finding evidence-based answers.', subjects: 'Physics, Chemistry, Biology, Mathematics, Computer Science', careerFamilies: 'Engineering, Medicine, Research, Technology, Biotechnology, Data Science, Architecture', indicators: 'You likely have strong Logic and Visual intelligence, left-brain dominance, and an Investigative or Realistic Holland type.' },
    Commerce: { name: 'Commerce Stream', color: '#27AE60', description: 'The Commerce stream suits you if you are good with numbers, communication, and organization. You might enjoy running businesses, managing finances, or persuading people. Commerce combines analytical thinking with people skills.', subjects: 'Accounting, Business Studies, Economics, Mathematics, Statistics', careerFamilies: 'Business Management, Finance, Banking, Marketing, Law, Entrepreneurship, Consulting', indicators: 'You likely have strong Linguistic and Logic intelligence, balanced brain, and an Enterprising or Conventional Holland type.' },
    Arts: { name: 'Arts Stream', color: '#9B59B6', description: 'The Arts stream is perfect if you are creative, expressive, and passionate about ideas and culture. You might love creating art, writing stories, performing music, or understanding human behavior.', subjects: 'Literature, History, Political Science, Psychology, Sociology, Fine Arts, Music', careerFamilies: 'Fine Arts, Literature, Performing Arts, Design, Psychology, Journalism, Filmmaking, Music, Architecture, Social Work', indicators: 'You likely have strong Imagination, Music, and Literature intelligence, right-brain dominance, and an Artistic or Social Holland type.' }
  };

  const learningStyles = {
    Visual: { name: 'Visual Learner', color: '#3498DB', description: 'You learn best when you can SEE information. Pictures, charts, diagrams, and written notes are your best friends. When someone tells you something, you automatically create a mental picture of it.', characteristics: ['Think in pictures and images', 'Remember faces better than names', 'Prefer reading over listening', 'Take detailed notes', 'Use color-coding and highlighting', 'Draw diagrams and mind maps'], studyTips: ['Use highlighters and colored pens', 'Create visual summaries and mind maps', 'Draw diagrams of concepts', 'Watch educational videos', 'Use flashcards with images', 'Convert notes into visual formats'], bestActivities: 'Watching demonstrations, reading illustrated books, creating diagrams, using color-coded systems, mind mapping' },
    Auditory: { name: 'Auditory Learner', color: '#E67E22', description: 'You learn best when you can HEAR information. Lectures, discussions, and audio recordings work great for you. You remember names better than faces, and you might talk to yourself or hum while studying.', characteristics: ['Remember names better than faces', 'Prefer listening to lectures over reading', 'Talk to yourself or hum', 'Read aloud or move lips while reading', 'Excellent verbal memory', 'Learn well in group discussions'], studyTips: ['Record lectures for replay', 'Read notes aloud', 'Explain concepts to study partners', 'Use word associations and mnemonics', 'Create songs or rhymes for memorization', 'Participate in study groups'], bestActivities: 'Listening to podcasts, participating in discussions, teaching others, using verbal mnemonics, audio recordings' },
    Kinesthetic: { name: 'Kinesthetic Learner', color: '#E74C3C', description: 'You learn best by DOING. Hands-on activities, experiments, and physical movement help you understand and remember. Sitting still for long periods is hard because your body needs to move to process information.', characteristics: ['Learn by doing, not by watching or listening', 'Fidgety, need to move while learning', 'Good at physical activities and sports', 'Prefer hands-on experiments', 'Remember events by what they did', 'Use gestures while speaking'], studyTips: ['Take frequent breaks to move', 'Use physical objects while studying', 'Stand up or walk while studying', 'Trace letters/words with finger', 'Use role-play to understand concepts', 'Chew gum or squeeze a stress ball'], bestActivities: 'Hands-on experiments, building models, role-playing, field trips, physical movement, interactive learning tools' }
  };

  const relationshipCompatibility = {
    'D-D': { level: 'Challenging', description: 'Two strong-willed leaders who both want control. Needs mutual respect and willingness to compromise. When it works, it\'s a powerful team.' },
    'D-I': { level: 'Strong', description: 'The driver and the motivator \u2014 a dynamic duo. The D-type provides direction and the I-type provides enthusiasm.' },
    'D-S': { level: 'Good', description: 'Leader and supporter \u2014 naturally balanced. The D-type makes decisions and the S-type provides steady support.' },
    'D-C': { level: 'Good', description: 'Vision and precision \u2014 the D-type drives forward and the C-type ensures quality.' },
    'I-I': { level: 'Fun', description: 'Two social butterflies \u2014 lots of fun! May lack organization and follow-through.' },
    'I-S': { level: 'Excellent', description: 'Warmth and support \u2014 very harmonious. The I-type brings energy and the S-type brings stability.' },
    'I-C': { level: 'Challenging', description: 'Social butterfly and introvert \u2014 different needs. Both must understand and appreciate differences.' },
    'S-S': { level: 'Good', description: 'Two peacemakers \u2014 very comfortable. May avoid necessary conflict.' },
    'S-C': { level: 'Good', description: 'Stability and structure \u2014 a reliable, predictable relationship. May lack excitement.' },
    'C-C': { level: 'Good but critical', description: 'Two perfectionists \u2014 very high standards. They understand each other but may be overly critical.' }
  };

  const parentingTips = {
    D: 'Give them choices and autonomy within limits. Set clear boundaries but let them make decisions. Don\'t be too controlling \u2014 they will push back. Praise their achievements and teach empathy early.',
    I: 'Give them attention and recognition. Encourage creativity but also teach follow-through. Help them organize their ideas into action. Celebrate social skills while building independence.',
    S: 'Provide a stable, predictable environment. Give them time to adjust to changes. Don\'t rush them into decisions. Praise reliability and gently encourage them to take small risks and speak up.',
    C: 'Appreciate their attention to detail and high standards. Help them understand mistakes are part of learning. Don\'t criticize harshly \u2014 they are already their own worst critic. Encourage breaks and fun.'
  };

  const stressManagement = {
    D: { triggers: 'Loss of control, inefficiency, being micromanaged', strategies: 'Physical exercise, competitive sports, having a clear action plan, taking control of small things first', warning: 'Becomes more demanding, impatient, and autocratic under stress' },
    I: { triggers: 'Social rejection, being ignored, loss of recognition', strategies: 'Talk to friends, creative expression, social activities, journaling feelings', warning: 'Becomes more dramatic, disorganized, and attention-seeking under stress' },
    S: { triggers: 'Sudden changes, instability, conflict, losing security', strategies: 'Maintain routines, nature walks, personal quiet time, talk to trusted friends', warning: 'Withdraws, becomes passive, stops communicating under stress' },
    C: { triggers: 'Making mistakes, disorder, criticism, unclear expectations', strategies: 'Organized problem-solving, detailed planning, alone time to think, research solutions', warning: 'Becomes more withdrawn, perfectionist, and self-critical under stress' }
  };

  const leadershipStyle = {
    D: { style: 'Authoritative/Directive', description: 'You lead by setting direction and making quick decisions. You are confident and inspire action. Your team knows exactly where you\'re going.', strengths: 'Decisive, confident, drives results, clear direction', growth: 'Practice active listening, delegate more, show vulnerability' },
    I: { style: 'Democratic/Inspirational', description: 'You lead by motivating and building enthusiasm. Your team loves working with you because you make it fun and meaningful.', strengths: 'Enthusiastic, creative, builds team spirit, persuasive', growth: 'Improve follow-through, develop organizational skills, set clear timelines' },
    S: { style: 'Servant/Supportive', description: 'You lead by serving and supporting your team. You develop people and build strong communities. Your team feels valued and cared for.', strengths: 'Patient, good listener, develops people, builds community', growth: 'Practice making faster decisions, learn to give constructive feedback, embrace change' },
    C: { style: 'Analytical/Strategic', description: 'You lead by planning meticulously and ensuring quality. Your team produces excellent work because you set high standards.', strengths: 'Analytical, quality-focused, systematic, reliable', growth: 'Accept "good enough" sometimes, make decisions with incomplete information, be more approachable' }
  };

  const emotionalIntelligence = {
    selfAwareness: { name: 'Self-Awareness', description: 'The ability to recognize and understand your own emotions, strengths, weaknesses, values, and motives. You know what you feel and why you feel it.' },
    selfRegulation: { name: 'Self-Regulation', description: 'The ability to manage your emotions and impulses. You can stay calm under pressure, think before acting, and adapt to changing circumstances.' },
    empathy: { name: 'Social Awareness (Empathy)', description: 'The ability to understand others\' emotions, needs, and concerns. You can "read the room" and sense how other people are feeling.' },
    socialSkills: { name: 'Relationship Management', description: 'The ability to influence, inspire, and develop others while managing conflict effectively. You can build and maintain healthy relationships.' }
  };

  const communicationStyle = {
    D: { style: 'Direct and Assertive', tips: 'Be brief, stick to business, offer options not just problems, be prepared for quick decisions', receiveBest: 'Bottom-line summaries, clear expectations, measurable goals', donts: 'Don\'t ramble, don\'t be vague, don\'t waste their time' },
    I: { style: 'Expressive and Enthusiastic', tips: 'Be friendly and warm, share stories, give recognition, allow time for socializing', receiveBest: 'Personal connection first, enthusiastic delivery, visual and engaging format', donts: 'Don\'t be cold or dismissive, don\'t skip social pleasantries, don\'t ignore their feelings' },
    S: { style: 'Thoughtful and Supportive', tips: 'Be patient, listen first, give time to process, provide reassurance, avoid surprises', receiveBest: 'Written summaries, advance notice, clear and gentle explanations, personal approach', donts: 'Don\'t rush them, don\'t spring sudden changes, don\'t be aggressive or confrontational' },
    C: { style: 'Precise and Analytical', tips: 'Be accurate and detailed, provide data and evidence, allow time for thinking, be organized', receiveBest: 'Written documentation, specific details, logical arguments, structured presentations', donts: 'Don\'t be vague, don\'t make claims without evidence, don\'t rush their analysis' }
  };

  const fingerRCMeaning = {
    L1: { brainLobe: 'Pre-frontal', function: 'Interpersonal Intelligence', hemisphere: 'Left', meaning: 'Your left thumb ridge count shows how strongly your interpersonal (people-smart) brain area developed. If the count is high, you naturally pick up on other people\'s feelings and moods. If it\'s low, you can still learn people skills — it just takes more practice.' },
    L2: { brainLobe: 'Frontal', function: 'Logical-Mathematical Intelligence', hemisphere: 'Left', meaning: 'Your left index finger ridge count shows how strongly your logical brain area developed. If the count is high, you naturally think in cause-and-effect patterns. If it\'s low, you can still develop logical thinking through practice and training.' },
    L3: { brainLobe: 'Parietal', function: 'Fine Motor Intelligence', hemisphere: 'Left', meaning: 'Your left middle finger ridge count shows how strongly your fine motor (hand skills) brain area developed. If the count is high, you naturally have precise hand control. If it\'s low, manual dexterity can still be developed through repetition.' },
    L4: { brainLobe: 'Temporal', function: 'Linguistic Intelligence', hemisphere: 'Left', meaning: 'Your left ring finger ridge count shows how strongly your language processing brain area developed. If the count is high, words come easily to you. If it\'s low, you can still become an excellent communicator with practice.' },
    L5: { brainLobe: 'Occipital', function: 'Visual Intelligence', hemisphere: 'Left', meaning: 'Your left little finger ridge count shows how strongly your visual processing brain area developed. If the count is high, you naturally notice visual details and remember pictures. If it\'s low, visual skills can still be improved with training.' },
    R1: { brainLobe: 'Pre-frontal', function: 'Interpersonal Intelligence', hemisphere: 'Right', meaning: 'Your right thumb ridge count shows how strongly your interpersonal (people-smart) brain area developed on the right side. The right side handles reading emotions and nonverbal cues. If the count is high, you naturally sense how others feel.' },
    R2: { brainLobe: 'Frontal', function: 'Imagination Intelligence', hemisphere: 'Right', meaning: 'Your right index finger ridge count shows how strongly your imaginative brain area developed. If the count is high, you naturally come up with creative ideas and "what if" thinking. If it\'s low, you can still develop creativity through practice.' },
    R3: { brainLobe: 'Parietal', function: 'Gross Motor Intelligence', hemisphere: 'Right', meaning: 'Your right middle finger ridge count shows how strongly your body-movement brain area developed. If the count is high, you naturally coordinate large body movements well. If it\'s low, physical skills can still be developed with practice.' },
    R4: { brainLobe: 'Temporal', function: 'Music Intelligence', hemisphere: 'Right', meaning: 'Your right ring finger ridge count shows how strongly your musical brain area developed. If the count is high, you naturally pick up rhythms, melodies, and tone. If it\'s low, musical ability can still be learned with dedication.' },
    R5: { brainLobe: 'Occipital', function: 'Visual/Spatial Intelligence', hemisphere: 'Right', meaning: 'Your right little finger ridge count shows how strongly your visual-spatial brain area developed. If the count is high, you naturally see patterns in space and navigate well. If it\'s low, spatial skills can still be improved.' },
  };

  const rcLevelDescriptions = {
    'Arch (Zero)': 'This brain area functions through other pathways. You may rely more on other intelligences to compensate. This is common and completely normal — many successful people have arch patterns on certain fingers.',
    'Lower': 'This area has less natural development, but think of it like a muscle that hasn\'t been exercised much yet. With focused practice and training, you can strengthen it significantly. Many skills are learned, not just innate.',
    'Average': 'This area has balanced development — a solid middle ground. You have a natural foundation that responds well to effort. Neither a special advantage nor a particular challenge.',
    'Higher': 'This area has stronger natural development. Think of it as having a head start in this domain. You likely feel drawn to activities that use this brain area. The key is to develop your gift rather than taking it for granted.',
  };

  const pairBalanceDescriptions = {
    'Balanced': 'Both sides of your brain process this function at a similar level. You likely have flexibility in how you approach this area — you can use both analytical and creative perspectives.',
    'Right stronger': 'Your right brain has a stronger natural development for this function. You probably approach it more intuitively, creatively, or holistically. Trust your gut feeling in this area.',
    'Left stronger': 'Your left brain has a stronger natural development for this function. You probably approach it more logically, sequentially, or analytically. Trust your reasoning in this area.',
    'Both arches': 'Neither hemisphere shows a strong innate preference for this function. You may have developed this skill through experience and practice rather than natural inclination.',
  };

  const bigFiveDescriptions = {
    O: {
      name: 'Openness to Experience',
      shortName: 'Openness',
      color: '#9B59B6',
      highDesc: 'You are curious, imaginative, and open to new ideas. You enjoy trying new things, thinking creatively, and exploring different perspectives. Routine bores you — you thrive on variety and intellectual stimulation.',
      lowDesc: 'You are practical, grounded, and prefer the familiar. You value proven methods over untested ideas. You don\'t need novelty to be happy — you find satisfaction in consistency and real-world results.',
      careerImplications: { high: 'Creative fields, research, entrepreneurship, arts, consulting', low: 'Operations, administration, finance, engineering, quality assurance' },
      relationshipImplications: { high: 'You need a partner who values new experiences and intellectual conversations. You may feel restless with someone who prefers routine.', low: 'You value stability and predictability in relationships. You show love through consistency, not surprises.' },
    },
    C: {
      name: 'Conscientiousness',
      shortName: 'Conscientiousness',
      color: '#2C3E50',
      highDesc: 'You are disciplined, organized, and goal-oriented. When you set a goal, you follow through. You keep promises, meet deadlines, and hold yourself to high standards. Just be careful not to burn out from perfectionism.',
      lowDesc: 'You are flexible, spontaneous, and prefer freedom over structure. You adapt easily to changing situations. Routine feels like a cage. You work best when you can choose how to organize your time and tasks.',
      careerImplications: { high: 'Management, law, accounting, project management, military, healthcare', low: 'Creative fields, startups, freelancing, consulting, research' },
      relationshipImplications: { high: 'You are reliable and follow through on commitments. You may sometimes seem rigid or overly focused on rules.', low: 'You bring spontaneity and flexibility. You may sometimes seem unreliable or disorganized to more structured partners.' },
    },
    E: {
      name: 'Extraversion',
      shortName: 'Extraversion',
      color: '#E74C3C',
      highDesc: 'You are energized by people and social interaction. You enjoy groups, discussions, and being in the center of action. You process things by talking them through. Solitude drains you — you recharge by connecting with others.',
      lowDesc: 'You are energized by quiet reflection and solitude. You prefer deep one-on-one conversations over large groups. You process things by thinking them through internally. Social interaction drains you — you recharge by being alone.',
      careerImplications: { high: 'Sales, teaching, management, politics, media, hospitality', low: 'Research, writing, programming, analysis, design, independent consulting' },
      relationshipImplications: { high: 'You bring energy and connection to relationships. You need social time to feel fulfilled. Just make sure you also listen.', low: 'You bring depth and thoughtfulness. You need personal space and quiet time. Just make sure you also share.' },
    },
    A: {
      name: 'Agreeableness',
      shortName: 'Agreeableness',
      color: '#27AE60',
      highDesc: 'You are warm, empathetic, and cooperative. You naturally trust people, want harmony, and put others\' needs before your own. You are a natural peacemaker. Just watch out for being too self-sacrificing.',
      lowDesc: 'You are direct, honest, and competitive. You value truth over comfort and aren\'t afraid to challenge others. You see things objectively. Just watch out for coming across as uncaring.',
      careerImplications: { high: 'Counseling, healthcare, teaching, social work, human resources, customer service', low: 'Law, consulting, management, research, military, auditing' },
      relationshipImplications: { high: 'You are a natural caretaker who prioritizes harmony. You may struggle to set boundaries or say no.', low: 'You are honest and direct. You may sometimes hurt feelings without meaning to, but you\'re also straightforward and genuine.' },
    },
    N: {
      name: 'Emotional Stability (Inverse Neuroticism)',
      shortName: 'Stability',
      color: '#3498DB',
      highDesc: 'You experience emotions intensely. You feel joy deeply but also feel stress, worry, and sadness more strongly. This sensitivity can be a superpower — it makes you empathetic and creative. The key is learning healthy coping strategies.',
      lowDesc: 'You are emotionally steady and calm under pressure. Stress doesn\'t shake you much. You are the rock others lean on. Your stability is a strength — just make sure you\'re not ignoring emotions that need attention.',
      careerImplications: { high: 'Arts, counseling, writing, therapy, creative fields, crisis management', low: 'Military, emergency services, executive leadership, surgery, air traffic control' },
      relationshipImplications: { high: 'You feel relationship ups and downs intensely. Communication and emotional support are essential for you.', low: 'You are a steady presence in relationships. You stay calm when things get tough. Just make sure you\'re not bottling up emotions.' },
    },
  };

  const strengthDomainDescriptions = {
    'Executing': { name: 'Executing', desc: 'You make things happen. You turn ideas into reality, organize chaos, and deliver results. Your domain theme says: "I will make it happen."', color: '#C04A1A' },
    'Influencing': { name: 'Influencing', desc: 'You inspire and persuade. You bring energy, direction, and enthusiasm to any situation. Your domain theme says: "I will take charge and rally others."', color: '#F39C12' },
    'Relationship Building': { name: 'Relationship Building', desc: 'You create strong, lasting connections. You build trust, understanding, and genuine relationships. Your domain theme says: "I will bring us together."', color: '#27AE60' },
    'Strategic Thinking': { name: 'Strategic Thinking', desc: 'You see possibilities and create paths forward. You absorb information, connect dots, and plan ahead. Your domain theme says: "I will figure it out."', color: '#2980B9' },
  };

  const workplaceDescriptions = {
    workStyle: 'Your work style describes how you naturally approach tasks, structure your day, and interact with colleagues. Understanding this helps you choose environments where you thrive.',
    decisionMaking: 'Your decision-making style reveals how you process information and reach conclusions. This affects everything from small daily choices to major life decisions.',
    conflictStyle: 'Your conflict style shows how you naturally react when opinions clash. Knowing this helps you navigate disagreements more effectively.',
    feedbackPreference: 'Your feedback preference tells you — and your managers — how you learn and grow best. Misaligned feedback is like watering a plant with the wrong nutrients.',
    motivationDrivers: 'These are the deep forces that get you out of bed in the morning. When your work aligns with your drivers, it doesn\'t feel like work.',
    riskTolerance: 'Your risk tolerance affects career choices, financial decisions, and life transitions. Neither high nor low risk tolerance is "better" — the key is knowing yours so you can make aligned choices.',
    idealManagerStyle: 'The type of manager who brings out your best work. Share this with your manager — they will appreciate knowing how to support you.',
    idealTeamRole: 'Your natural team role is the one where you contribute most effectively. Great teams have a mix of all four roles — Drivers, Energizers, Stabilizers, and Analysts.',
  };

  const careerTransitionInfo = {
    transferableSkillsHeader: 'Skills That Transfer',
    transferableSkillsDesc: 'These are skills you have from your current intelligence strengths that apply across many jobs and industries. Even if you change careers completely, these come with you.',
    bridgeCareersHeader: 'Bridge Careers',
    bridgeCareersDesc: 'Bridge careers are roles that leverage your existing strengths while developing new ones. They are a smart way to transition without starting from zero.',
  };

  const cognitiveReserveInfo = {
    description: 'Think of cognitive reserve as your brain\'s savings account. The more diverse your intelligence strengths, the more "money" is in that account. When challenges come — whether it\'s a tough project at work or the normal changes that come with aging — your brain can draw from this reserve. It\'s not about being "smart" in one area; it\'s about having many different ways to think.',
    interpretation: {
      High: 'You have intelligence strengths across multiple areas. This gives you strong cognitive flexibility — you can approach problems from many angles. Keep developing all your strengths, not just the top ones.',
      Moderate: 'You have a solid foundation with some standout areas. You can strengthen your reserve by deliberately developing weaker areas through practice and new experiences.',
      Developing: 'Your intelligences are concentrated in fewer areas. This means you\'re very strong in specific domains, but you could benefit from cross-training — trying activities outside your comfort zone to build new neural pathways.',
    },
  };

  const wellnessInfo = {
    stressSignatureDesc: 'Your stress signature describes how stress physically, emotionally, and cognitively shows up for you. Knowing this helps you recognize stress early — before it builds up.',
    recoveryActivitiesDesc: 'These activities are specifically chosen because they match your intelligence strengths. When stress relief aligns with your natural strengths, it\'s more effective.',
    socialNeedsDesc: 'Your social needs describe how much interaction you require to feel energized and balanced. This is different from extraversion — it\'s about the quality and quantity of human connection that recharges you.',
    purposeAlignmentDesc: 'Your purpose alignment shows what gives your life meaning and direction, based on your intelligence strengths. When your work and activities align with your purpose, you feel fulfilled.',
  };

  const perFingerDescriptions = {
    L1: { name: 'Left Thumb', brainRegion: 'Pre-frontal Cortex', intelligence: 'Interpersonal', description: 'The left thumb connects to how you process interpersonal intelligence in a logical, structured way. You understand people through observation and analysis. A higher ridge count here means you naturally "read" social situations logically.' },
    L2: { name: 'Left Index', brainRegion: 'Frontal Lobe', intelligence: 'Logical-Mathematical', description: 'The left index finger connects to your logical-mathematical brain — the part that solves problems step by step, works with numbers, and finds patterns. A higher count means logical thinking comes more naturally to you.' },
    L3: { name: 'Left Middle', brainRegion: 'Parietal Lobe', intelligence: 'Fine Motor', description: 'The left middle finger connects to fine motor skills — your hands\' precision and coordination. A higher count means you naturally have good hand control for detailed work like writing, drawing, or building.' },
    L4: { name: 'Left Ring', brainRegion: 'Temporal Lobe', intelligence: 'Linguistic', description: 'The left ring finger connects to language processing — how you understand and use words effectively. A higher count means words, grammar, and verbal reasoning come more naturally to you.' },
    L5: { name: 'Left Little', brainRegion: 'Occipital Lobe', intelligence: 'Visual Processing', description: 'The left little finger connects to visual detail processing — how you notice and remember visual information. A higher count means you\'re naturally good at seeing details others might miss.' },
    R1: { name: 'Right Thumb', brainRegion: 'Pre-frontal Cortex', intelligence: 'Interpersonal', description: 'The right thumb connects to interpersonal intelligence in an intuitive, emotional way. You understand people through feeling, not just thinking. A higher count means you naturally sense what others are experiencing.' },
    R2: { name: 'Right Index', brainRegion: 'Frontal Lobe', intelligence: 'Imagination', description: 'The right index finger connects to your imagination — the part that generates "what if" ideas and sees possibilities. A higher count means creative thinking and brainstorming come naturally to you.' },
    R3: { name: 'Right Middle', brainRegion: 'Parietal Lobe', intelligence: 'Gross Motor', description: 'The right middle finger connects to gross motor skills — whole-body movement like running, jumping, and coordinating physical activities. A higher count means you naturally move well and learn physical skills quickly.' },
    R4: { name: 'Right Ring', brainRegion: 'Temporal Lobe', intelligence: 'Musical', description: 'The right ring finger connects to musical ability — rhythm, pitch, melody, and emotional expression through sound. A higher count means you naturally pick up rhythms and respond deeply to music.' },
    R5: { name: 'Right Little', brainRegion: 'Occipital Lobe', intelligence: 'Visual/Spatial', description: 'The right little finger connects to visual-spatial processing — how you navigate space, see the big picture, and think in images. A higher count means you naturally see how things fit together in space.' },
  };

  const brainLobeInfo = {
    'Pre-frontal': { name: 'Pre-frontal Cortex', function: 'Executive function, planning, decision-making, imagination', description: 'The pre-frontal cortex is your brain\'s CEO. It handles planning, decision-making, and imaginative thinking. Strong development here means you are a natural strategist and visionary.' },
    'Frontal': { name: 'Frontal Lobe', function: 'Logic, reasoning, interpersonal skills, leadership', description: 'The frontal lobe powers your logical reasoning and social intelligence. It is the seat of your analytical mind and your ability to lead and communicate effectively.' },
    'Parietal': { name: 'Parietal Lobe', function: 'Motor skills, sensory integration, body awareness', description: 'The parietal lobe coordinates movement and sensory information. Strong development here gives you excellent physical coordination and spatial awareness.' },
    'Temporal': { name: 'Temporal Lobe', function: 'Language, music, auditory processing, memory', description: 'The temporal lobe processes sound, language, and music. It is essential for verbal communication, musical ability, and memory formation.' },
    'Occipital': { name: 'Occipital Lobe', function: 'Visual processing, pattern recognition, observation', description: 'The occipital lobe is your visual center. It processes what you see and helps you recognize patterns, navigate space, and notice details.' },
  };

  const subIntelligenceInfo = {
    planning: { name: 'Planning', parent: 'Logical', description: 'Your ability to organize steps and anticipate outcomes.' },
    reasoning: { name: 'Reasoning', parent: 'Logical', description: 'Your capacity to draw logical conclusions from evidence.' },
    numerical: { name: 'Numerical', parent: 'Logical', description: 'Your comfort and skill with numbers and quantitative thinking.' },
    geometry: { name: 'Geometry', parent: 'Logical', description: 'Your ability to understand shapes, spaces, and spatial relationships.' },
    verbal: { name: 'Verbal', parent: 'Linguistic', description: 'Your skill in spoken communication and word fluency.' },
    writing: { name: 'Writing', parent: 'Linguistic', description: 'Your ability to express ideas clearly through written language.' },
    nonverbal: { name: 'Non-Verbal', parent: 'Visual', description: 'Your ability to communicate and understand without words.' },
    observation: { name: 'Observation', parent: 'Visual', description: 'Your skill in noticing details and environmental cues.' },
    threed: { name: '3D Ideas', parent: 'Imagination', description: 'Your ability to visualize and manipulate objects in three dimensions.' },
    social: { name: 'Social', parent: 'Interpersonal', description: 'Your ease in navigating social situations and group dynamics.' },
    emotion: { name: 'Emotion', parent: 'Interpersonal', description: 'Your sensitivity to emotional undercurrents in others.' },
    motivation: { name: 'Motivation', parent: 'Intrapersonal', description: 'Your drive to set and pursue personal goals.' },
    voicetone: { name: 'Voice Tone', parent: 'Musical', description: 'Your sensitivity to pitch, tone, and vocal expression.' },
    processing: { name: 'Processing', parent: 'Musical', description: 'Your speed and accuracy in processing auditory information.' },
    grossmotor: { name: 'Gross Motor', parent: 'Kinesthetic', description: 'Your control over large muscle groups and whole-body movement.' },
    finemotor: { name: 'Fine Motor', parent: 'Kinesthetic', description: 'Your precision and dexterity in small, controlled movements.' },
    senses: { name: 'Senses', parent: 'Naturalist', description: 'Your sensitivity to sensory input from the natural world.' },
    spiritual: { name: 'Spiritual', parent: 'Intrapersonal', description: 'Your inclination toward meaning, purpose, and reflection.' },
    inter: { name: 'Interpersonal', parent: 'Interpersonal', description: 'Your overall people skills and relational intelligence.' },
  };

  const acquiringMethodsInfo = {
    'Experiential Learning': { title: 'Experiential Learning', description: 'You acquire knowledge fastest through direct experience. Labs, internships, field trips, and hands-on projects should be your primary learning modes.' },
    'Auditory Acquisition': { title: 'Auditory Acquisition', description: 'Listening is your superpower. Podcasts, lectures, group discussions, and verbal explanations help you retain information with remarkable accuracy.' },
    'Visual Learning': { title: 'Visual Learning', description: 'Your brain thinks in pictures. Use diagrams, infographics, color-coded notes, and video content to accelerate your learning.' },
    'Action-Oriented': { title: 'Action-Oriented', description: 'You learn best when there is a clear objective and immediate application. Set goals before studying and apply concepts right away.' },
    'Social Learning': { title: 'Social Learning', description: 'Learning is a team sport for you. Study groups, peer teaching, and collaborative projects dramatically improve your retention.' },
    'Reflective Practice': { title: 'Reflective Practice', description: 'You need time to digest information. After each session, write a summary or teach the concept to yourself out loud.' },
    'Structured Study': { title: 'Structured Study', description: 'You thrive on detailed syllabi, logical sequencing, and evidence-based content. Create study schedules and stick to them.' },
    'Tactile Engagement': { title: 'Tactile Engagement', description: 'Touch reinforces memory for you. Take notes by hand, build physical models, and use manipulatives whenever possible.' },
    'Observational Learning': { title: 'Observational Learning', description: 'Watching experts at work is your fastest path to mastery. Shadow mentors, watch tutorials, and attend live demonstrations.' },
  };

  return {
    brainDominance, intelligences, fingerprintPersonalities, discTypes,
    hollandTypes, mckenzieTypes, quotients, atdAngle, streamRecommendation,
    learningStyles, relationshipCompatibility, parentingTips, stressManagement,
    leadershipStyle, emotionalIntelligence, communicationStyle,
    fingerRCMeaning, rcLevelDescriptions, pairBalanceDescriptions,
    bigFiveDescriptions, strengthDomainDescriptions, workplaceDescriptions,
    careerTransitionInfo, cognitiveReserveInfo, wellnessInfo,
    perFingerDescriptions, brainLobeInfo, subIntelligenceInfo, acquiringMethodsInfo,
  };
})();
